/* OpenSyncro - A web-based enterprise application integration tool
 * Copyright (C) 2008 Smilehouse Oy, support@opensyncro.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package smilehouse.openinterface;


public class CustomerCriteria {
    protected java.util.Calendar adminModifiedAfter;
    protected java.util.Calendar adminModifiedBefore;
    protected java.lang.String customerGroup;
    protected java.lang.String customerId;
    protected java.util.Calendar customerModifiedAfter;
    protected java.util.Calendar customerModifiedBefore;
    protected java.util.Calendar firstVisitDateAfter;
    protected java.util.Calendar firstVisitDateBefore;
    protected java.lang.String idGreaterThan;
    protected java.lang.String[] idIn;
    protected java.lang.String idLessThan;
    protected java.util.Calendar lastVisitDateAfter;
    protected java.util.Calendar lastVisitDateBefore;
    protected java.lang.String modifyOperation;
    protected java.lang.String primaryCustomerGroup;
    
    public CustomerCriteria() {
    }
    
    public CustomerCriteria(java.util.Calendar adminModifiedAfter, java.util.Calendar adminModifiedBefore, java.lang.String customerGroup, java.lang.String customerId, java.util.Calendar customerModifiedAfter, java.util.Calendar customerModifiedBefore, java.util.Calendar firstVisitDateAfter, java.util.Calendar firstVisitDateBefore, java.lang.String idGreaterThan, java.lang.String[] idIn, java.lang.String idLessThan, java.util.Calendar lastVisitDateAfter, java.util.Calendar lastVisitDateBefore, java.lang.String modifyOperation, java.lang.String primaryCustomerGroup) {
        this.adminModifiedAfter = adminModifiedAfter;
        this.adminModifiedBefore = adminModifiedBefore;
        this.customerGroup = customerGroup;
        this.customerId = customerId;
        this.customerModifiedAfter = customerModifiedAfter;
        this.customerModifiedBefore = customerModifiedBefore;
        this.firstVisitDateAfter = firstVisitDateAfter;
        this.firstVisitDateBefore = firstVisitDateBefore;
        this.idGreaterThan = idGreaterThan;
        this.idIn = idIn;
        this.idLessThan = idLessThan;
        this.lastVisitDateAfter = lastVisitDateAfter;
        this.lastVisitDateBefore = lastVisitDateBefore;
        this.modifyOperation = modifyOperation;
        this.primaryCustomerGroup = primaryCustomerGroup;
    }
    
    public java.util.Calendar getAdminModifiedAfter() {
        return adminModifiedAfter;
    }
    
    public void setAdminModifiedAfter(java.util.Calendar adminModifiedAfter) {
        this.adminModifiedAfter = adminModifiedAfter;
    }
    
    public java.util.Calendar getAdminModifiedBefore() {
        return adminModifiedBefore;
    }
    
    public void setAdminModifiedBefore(java.util.Calendar adminModifiedBefore) {
        this.adminModifiedBefore = adminModifiedBefore;
    }
    
    public java.lang.String getCustomerGroup() {
        return customerGroup;
    }
    
    public void setCustomerGroup(java.lang.String customerGroup) {
        this.customerGroup = customerGroup;
    }
    
    public java.lang.String getCustomerId() {
        return customerId;
    }
    
    public void setCustomerId(java.lang.String customerId) {
        this.customerId = customerId;
    }
    
    public java.util.Calendar getCustomerModifiedAfter() {
        return customerModifiedAfter;
    }
    
    public void setCustomerModifiedAfter(java.util.Calendar customerModifiedAfter) {
        this.customerModifiedAfter = customerModifiedAfter;
    }
    
    public java.util.Calendar getCustomerModifiedBefore() {
        return customerModifiedBefore;
    }
    
    public void setCustomerModifiedBefore(java.util.Calendar customerModifiedBefore) {
        this.customerModifiedBefore = customerModifiedBefore;
    }
    
    public java.util.Calendar getFirstVisitDateAfter() {
        return firstVisitDateAfter;
    }
    
    public void setFirstVisitDateAfter(java.util.Calendar firstVisitDateAfter) {
        this.firstVisitDateAfter = firstVisitDateAfter;
    }
    
    public java.util.Calendar getFirstVisitDateBefore() {
        return firstVisitDateBefore;
    }
    
    public void setFirstVisitDateBefore(java.util.Calendar firstVisitDateBefore) {
        this.firstVisitDateBefore = firstVisitDateBefore;
    }
    
    public java.lang.String getIdGreaterThan() {
        return idGreaterThan;
    }
    
    public void setIdGreaterThan(java.lang.String idGreaterThan) {
        this.idGreaterThan = idGreaterThan;
    }
    
    public java.lang.String[] getIdIn() {
        return idIn;
    }
    
    public void setIdIn(java.lang.String[] idIn) {
        this.idIn = idIn;
    }
    
    public java.lang.String getIdLessThan() {
        return idLessThan;
    }
    
    public void setIdLessThan(java.lang.String idLessThan) {
        this.idLessThan = idLessThan;
    }
    
    public java.util.Calendar getLastVisitDateAfter() {
        return lastVisitDateAfter;
    }
    
    public void setLastVisitDateAfter(java.util.Calendar lastVisitDateAfter) {
        this.lastVisitDateAfter = lastVisitDateAfter;
    }
    
    public java.util.Calendar getLastVisitDateBefore() {
        return lastVisitDateBefore;
    }
    
    public void setLastVisitDateBefore(java.util.Calendar lastVisitDateBefore) {
        this.lastVisitDateBefore = lastVisitDateBefore;
    }
    
    public java.lang.String getModifyOperation() {
        return modifyOperation;
    }
    
    public void setModifyOperation(java.lang.String modifyOperation) {
        this.modifyOperation = modifyOperation;
    }
    
    public java.lang.String getPrimaryCustomerGroup() {
        return primaryCustomerGroup;
    }
    
    public void setPrimaryCustomerGroup(java.lang.String primaryCustomerGroup) {
        this.primaryCustomerGroup = primaryCustomerGroup;
    }
}
