/* OpenSyncro - A web-based enterprise application integration tool
 * Copyright (C) 2008 Smilehouse Oy, support@opensyncro.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package smilehouse.openinterface;


public class ImportResult {
    protected java.util.List insertedIds;
    protected java.util.List removedIds;
    protected java.util.List updatedIds;
    protected java.util.List warnings;
    
    public ImportResult() {
    }
    
    public ImportResult(java.util.List insertedIds, java.util.List removedIds, java.util.List updatedIds, java.util.List warnings) {
        this.insertedIds = insertedIds;
        this.removedIds = removedIds;
        this.updatedIds = updatedIds;
        this.warnings = warnings;
    }
    
    public java.util.List getInsertedIds() {
        return insertedIds;
    }
    
    public void setInsertedIds(java.util.List insertedIds) {
        this.insertedIds = insertedIds;
    }
    
    public java.util.List getRemovedIds() {
        return removedIds;
    }
    
    public void setRemovedIds(java.util.List removedIds) {
        this.removedIds = removedIds;
    }
    
    public java.util.List getUpdatedIds() {
        return updatedIds;
    }
    
    public void setUpdatedIds(java.util.List updatedIds) {
        this.updatedIds = updatedIds;
    }
    
    public java.util.List getWarnings() {
        return warnings;
    }
    
    public void setWarnings(java.util.List warnings) {
        this.warnings = warnings;
    }
}
