/* OpenSyncro - A web-based enterprise application integration tool
 * Copyright (C) 2008 Smilehouse Oy, support@opensyncro.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package smilehouse.openinterface;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class ImportResult_SOAPBuilder implements SOAPInstanceBuilder {
    private smilehouse.openinterface.ImportResult _instance;
    private java.util.List insertedIds;
    private java.util.List removedIds;
    private java.util.List updatedIds;
    private java.util.List warnings;
    private static final int myINSERTEDIDS_INDEX = 0;
    private static final int myREMOVEDIDS_INDEX = 1;
    private static final int myUPDATEDIDS_INDEX = 2;
    private static final int myWARNINGS_INDEX = 3;
    
    public ImportResult_SOAPBuilder() {
    }
    
    public void setInsertedIds(java.util.List insertedIds) {
        this.insertedIds = insertedIds;
    }
    
    public void setRemovedIds(java.util.List removedIds) {
        this.removedIds = removedIds;
    }
    
    public void setUpdatedIds(java.util.List updatedIds) {
        this.updatedIds = updatedIds;
    }
    
    public void setWarnings(java.util.List warnings) {
        this.warnings = warnings;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myINSERTEDIDS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myREMOVEDIDS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myUPDATEDIDS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myWARNINGS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, Object memberValue) {
        try {
            switch(index) {
                case myINSERTEDIDS_INDEX:
                    _instance.setInsertedIds((java.util.List)memberValue);
                    break;
                case myREMOVEDIDS_INDEX:
                    _instance.setRemovedIds((java.util.List)memberValue);
                    break;
                case myUPDATEDIDS_INDEX:
                    _instance.setUpdatedIds((java.util.List)memberValue);
                    break;
                case myWARNINGS_INDEX:
                    _instance.setWarnings((java.util.List)memberValue);
                    break;
                default:
                    throw new IllegalArgumentException();
            }
        }
        catch (RuntimeException e) {
            throw e;
        }
        catch (Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(Object instance) {
        _instance = (smilehouse.openinterface.ImportResult)instance;
    }
    
    public Object getInstance() {
        return _instance;
    }
}
