/* OpenSyncro - A web-based enterprise application integration tool
 * Copyright (C) 2008 Smilehouse Oy, support@opensyncro.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package smilehouse.openinterface;


public class OpenInterfaceIF_importProducts2_RequestStruct {
    protected smilehouse.openinterface.LoginInfo loginInfo_1;
    protected java.lang.String string_2;
    protected int int_3;
    protected boolean boolean_4;
    protected boolean boolean_5;
    protected java.lang.String[] arrayOfString_6;
    protected boolean boolean_7;
    
    public OpenInterfaceIF_importProducts2_RequestStruct() {
    }
    
    public OpenInterfaceIF_importProducts2_RequestStruct(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2, int int_3, boolean boolean_4, boolean boolean_5, java.lang.String[] arrayOfString_6, boolean boolean_7) {
        this.loginInfo_1 = loginInfo_1;
        this.string_2 = string_2;
        this.int_3 = int_3;
        this.boolean_4 = boolean_4;
        this.boolean_5 = boolean_5;
        this.arrayOfString_6 = arrayOfString_6;
        this.boolean_7 = boolean_7;
    }
    
    public smilehouse.openinterface.LoginInfo getLoginInfo_1() {
        return loginInfo_1;
    }
    
    public void setLoginInfo_1(smilehouse.openinterface.LoginInfo loginInfo_1) {
        this.loginInfo_1 = loginInfo_1;
    }
    
    public java.lang.String getString_2() {
        return string_2;
    }
    
    public void setString_2(java.lang.String string_2) {
        this.string_2 = string_2;
    }
    
    public int getInt_3() {
        return int_3;
    }
    
    public void setInt_3(int int_3) {
        this.int_3 = int_3;
    }
    
    public boolean isBoolean_4() {
        return boolean_4;
    }
    
    public void setBoolean_4(boolean boolean_4) {
        this.boolean_4 = boolean_4;
    }
    
    public boolean isBoolean_5() {
        return boolean_5;
    }
    
    public void setBoolean_5(boolean boolean_5) {
        this.boolean_5 = boolean_5;
    }
    
    public java.lang.String[] getArrayOfString_6() {
        return arrayOfString_6;
    }
    
    public void setArrayOfString_6(java.lang.String[] arrayOfString_6) {
        this.arrayOfString_6 = arrayOfString_6;
    }
    
    public boolean isBoolean_7() {
        return boolean_7;
    }
    
    public void setBoolean_7(boolean boolean_7) {
        this.boolean_7 = boolean_7;
    }
}
