/* OpenSyncro - A web-based enterprise application integration tool
 * Copyright (C) 2008 Smilehouse Oy, support@opensyncro.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package smilehouse.openinterface;

public interface OpenInterfaceIF extends java.rmi.Remote {
    public void closeIterator(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2) throws 
        smilehouse.openinterface.OpenInterfaceException, smilehouse.openinterface.AccessDeniedException,  java.rmi.RemoteException;
    public smilehouse.openinterface.ExportResult exportCustomers(smilehouse.openinterface.LoginInfo loginInfo_1, smilehouse.openinterface.CustomerCriteria customerCriteria_2) throws 
        smilehouse.openinterface.OpenInterfaceException, smilehouse.openinterface.AccessDeniedException,  java.rmi.RemoteException;
    public smilehouse.openinterface.ExportResult exportOrderXML(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, smilehouse.openinterface.OrderCriteria orderCriteria_4, java.lang.Long long_5) throws 
        smilehouse.openinterface.AccessDeniedException, smilehouse.openinterface.OpenInterfaceException,  java.rmi.RemoteException;
    public smilehouse.openinterface.ExportResult exportOrders(smilehouse.openinterface.LoginInfo loginInfo_1, smilehouse.openinterface.OrderCriteria orderCriteria_2, java.lang.Long long_3, java.lang.String string_4) throws 
        smilehouse.openinterface.OpenInterfaceException, smilehouse.openinterface.AccessDeniedException,  java.rmi.RemoteException;
    public smilehouse.openinterface.ExportResult exportOrders2(smilehouse.openinterface.LoginInfo loginInfo_1, smilehouse.openinterface.OrderCriteria orderCriteria_2, java.lang.String string_3) throws 
        smilehouse.openinterface.AccessDeniedException, smilehouse.openinterface.OpenInterfaceException,  java.rmi.RemoteException;
    public double getVersion() throws 
         java.rmi.RemoteException;
    public smilehouse.openinterface.ImportResult importCustomers(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2, int int_3, boolean boolean_4) throws 
        smilehouse.openinterface.AccessDeniedException, smilehouse.openinterface.OpenInterfaceException,  java.rmi.RemoteException;
    public smilehouse.openinterface.ImportResult importOrders(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2, int int_3, boolean boolean_4, boolean boolean_5, boolean boolean_6) throws 
        smilehouse.openinterface.AccessDeniedException, smilehouse.openinterface.OpenInterfaceException,  java.rmi.RemoteException;
    public smilehouse.openinterface.ImportResult importPricelist(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2, int int_3) throws 
        smilehouse.openinterface.OpenInterfaceException, smilehouse.openinterface.AccessDeniedException,  java.rmi.RemoteException;
    public smilehouse.openinterface.ImportResult importProducts(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2, int int_3, java.lang.String[] arrayOfString_4, boolean boolean_5, boolean boolean_6) throws 
        smilehouse.openinterface.OpenInterfaceException, smilehouse.openinterface.AccessDeniedException,  java.rmi.RemoteException;
    public smilehouse.openinterface.ImportResult importProducts2(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2, int int_3, boolean boolean_4, boolean boolean_5, java.lang.String[] arrayOfString_6, boolean boolean_7) throws 
        smilehouse.openinterface.OpenInterfaceException, smilehouse.openinterface.AccessDeniedException,  java.rmi.RemoteException;
    public void invokeEvent(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2, java.lang.Object object_3) throws 
        smilehouse.openinterface.AccessDeniedException, smilehouse.openinterface.OpenInterfaceException,  java.rmi.RemoteException;
    public smilehouse.openinterface.ExportResult iterate(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2, int int_3) throws 
        smilehouse.openinterface.OpenInterfaceException, smilehouse.openinterface.AccessDeniedException, smilehouse.openinterface.IteratorClosedException,  java.rmi.RemoteException;
    public java.lang.String openHQLIterator(smilehouse.openinterface.LoginInfo loginInfo_1, java.lang.String string_2, long long_3) throws 
        smilehouse.openinterface.AccessDeniedException, smilehouse.openinterface.OpenInterfaceException,  java.rmi.RemoteException;
}
