/* OpenSyncro - A web-based enterprise application integration tool
 * Copyright (C) 2008 Smilehouse Oy, support@opensyncro.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package smilehouse.openinterface;


public class OpenInterfaceIF_exportOrderXML_RequestStruct {
    protected java.lang.String string_1;
    protected java.lang.String string_2;
    protected java.lang.String string_3;
    protected smilehouse.openinterface.OrderCriteria orderCriteria_4;
    protected java.lang.Long long_5;
    
    public OpenInterfaceIF_exportOrderXML_RequestStruct() {
    }
    
    public OpenInterfaceIF_exportOrderXML_RequestStruct(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, smilehouse.openinterface.OrderCriteria orderCriteria_4, java.lang.Long long_5) {
        this.string_1 = string_1;
        this.string_2 = string_2;
        this.string_3 = string_3;
        this.orderCriteria_4 = orderCriteria_4;
        this.long_5 = long_5;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_2() {
        return string_2;
    }
    
    public void setString_2(java.lang.String string_2) {
        this.string_2 = string_2;
    }
    
    public java.lang.String getString_3() {
        return string_3;
    }
    
    public void setString_3(java.lang.String string_3) {
        this.string_3 = string_3;
    }
    
    public smilehouse.openinterface.OrderCriteria getOrderCriteria_4() {
        return orderCriteria_4;
    }
    
    public void setOrderCriteria_4(smilehouse.openinterface.OrderCriteria orderCriteria_4) {
        this.orderCriteria_4 = orderCriteria_4;
    }
    
    public java.lang.Long getLong_5() {
        return long_5;
    }
    
    public void setLong_5(java.lang.Long long_5) {
        this.long_5 = long_5;
    }
}
