/* OpenSyncro - A web-based enterprise application integration tool
 * Copyright (C) 2008 Smilehouse Oy, support@opensyncro.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package smilehouse.openinterface;


public class OrderCriteria {
    protected java.lang.String[] customerIdIn;
    protected java.util.Calendar dateAfter;
    protected java.util.Calendar dateBefore;
    protected java.lang.String[] handlingStatusNameIn;
    protected java.lang.String[] handlingStatusNameNotIn;
    protected java.lang.Long idGreaterThan;
    protected java.lang.Long[] idIn;
    protected java.lang.Long idLessThan;
    protected java.lang.String[] paymentStatusNameIn;
    protected java.lang.String[] paymentStatusNameNotIn;
    protected smilehouse.openinterface.OrderCriteriaSortRule[] sortRules;
    protected java.lang.Double sumGreaterThan;
    protected java.lang.Double sumLessThan;
    
    public OrderCriteria() {
    }
    
    public OrderCriteria(java.lang.String[] customerIdIn, java.util.Calendar dateAfter, java.util.Calendar dateBefore, java.lang.String[] handlingStatusNameIn, java.lang.String[] handlingStatusNameNotIn, java.lang.Long idGreaterThan, java.lang.Long[] idIn, java.lang.Long idLessThan, java.lang.String[] paymentStatusNameIn, java.lang.String[] paymentStatusNameNotIn, smilehouse.openinterface.OrderCriteriaSortRule[] sortRules, java.lang.Double sumGreaterThan, java.lang.Double sumLessThan) {
        this.customerIdIn = customerIdIn;
        this.dateAfter = dateAfter;
        this.dateBefore = dateBefore;
        this.handlingStatusNameIn = handlingStatusNameIn;
        this.handlingStatusNameNotIn = handlingStatusNameNotIn;
        this.idGreaterThan = idGreaterThan;
        this.idIn = idIn;
        this.idLessThan = idLessThan;
        this.paymentStatusNameIn = paymentStatusNameIn;
        this.paymentStatusNameNotIn = paymentStatusNameNotIn;
        this.sortRules = sortRules;
        this.sumGreaterThan = sumGreaterThan;
        this.sumLessThan = sumLessThan;
    }
    
    public java.lang.String[] getCustomerIdIn() {
        return customerIdIn;
    }
    
    public void setCustomerIdIn(java.lang.String[] customerIdIn) {
        this.customerIdIn = customerIdIn;
    }
    
    public java.util.Calendar getDateAfter() {
        return dateAfter;
    }
    
    public void setDateAfter(java.util.Calendar dateAfter) {
        this.dateAfter = dateAfter;
    }
    
    public java.util.Calendar getDateBefore() {
        return dateBefore;
    }
    
    public void setDateBefore(java.util.Calendar dateBefore) {
        this.dateBefore = dateBefore;
    }
    
    public java.lang.String[] getHandlingStatusNameIn() {
        return handlingStatusNameIn;
    }
    
    public void setHandlingStatusNameIn(java.lang.String[] handlingStatusNameIn) {
        this.handlingStatusNameIn = handlingStatusNameIn;
    }
    
    public java.lang.String[] getHandlingStatusNameNotIn() {
        return handlingStatusNameNotIn;
    }
    
    public void setHandlingStatusNameNotIn(java.lang.String[] handlingStatusNameNotIn) {
        this.handlingStatusNameNotIn = handlingStatusNameNotIn;
    }
    
    public java.lang.Long getIdGreaterThan() {
        return idGreaterThan;
    }
    
    public void setIdGreaterThan(java.lang.Long idGreaterThan) {
        this.idGreaterThan = idGreaterThan;
    }
    
    public java.lang.Long[] getIdIn() {
        return idIn;
    }
    
    public void setIdIn(java.lang.Long[] idIn) {
        this.idIn = idIn;
    }
    
    public java.lang.Long getIdLessThan() {
        return idLessThan;
    }
    
    public void setIdLessThan(java.lang.Long idLessThan) {
        this.idLessThan = idLessThan;
    }
    
    public java.lang.String[] getPaymentStatusNameIn() {
        return paymentStatusNameIn;
    }
    
    public void setPaymentStatusNameIn(java.lang.String[] paymentStatusNameIn) {
        this.paymentStatusNameIn = paymentStatusNameIn;
    }
    
    public java.lang.String[] getPaymentStatusNameNotIn() {
        return paymentStatusNameNotIn;
    }
    
    public void setPaymentStatusNameNotIn(java.lang.String[] paymentStatusNameNotIn) {
        this.paymentStatusNameNotIn = paymentStatusNameNotIn;
    }
    
    public smilehouse.openinterface.OrderCriteriaSortRule[] getSortRules() {
        return sortRules;
    }
    
    public void setSortRules(smilehouse.openinterface.OrderCriteriaSortRule[] sortRules) {
        this.sortRules = sortRules;
    }
    
    public java.lang.Double getSumGreaterThan() {
        return sumGreaterThan;
    }
    
    public void setSumGreaterThan(java.lang.Double sumGreaterThan) {
        this.sumGreaterThan = sumGreaterThan;
    }
    
    public java.lang.Double getSumLessThan() {
        return sumLessThan;
    }
    
    public void setSumLessThan(java.lang.Double sumLessThan) {
        this.sumLessThan = sumLessThan;
    }
}
